### ISSUE TITLE
Use @Generated annotation

### ISSUE THREAD

**Issue by emartynov** [soundcloud/delect#19]
Reading https://stackoverflow.com/questions/10483053/generated-annotation-how-do-we-use-it I'm not sure if it is good/necessary practice at all. 

I leave it here for the discussion.

**Comment by runningcode** [comment]
If you are asking if the generated code should use the `@Generated` annotation, please file that ticket against the dagger reflect code generator. https://github.com/jakewharton/dagger-reflect

**Comment by emartynov** [comment]
Thank you! Created https://github.com/JakeWharton/dagger-reflect/issues/172
