### ISSUE TITLE
Use shallow clone and docker image with gradle

### ISSUE THREAD

**Issue by emartynov** [soundcloud/delect#20]
These are essential for me to have speed up the builds.

**Comment by runningcode** [comment]
Sorry, I'm missing some context. What exactly is being shallow cloned here? What docker image?

**Comment by emartynov** [comment]
Example: `git clone --depth 1 https://github.com/django/django.git` (https://linuxhint.com/git-shallow-clone-and-clone-depth/). I don't know if your CI provider supports it. Sorry didn't check it.

Ah, you already are using (https://hub.docker.com/_/gradle). To stop downloading gradle every build you have to use `gradle` instead of `gradlew`.

**Comment by emartynov** [comment]
Closing as a non-important idea
