### ISSUE TITLE
[Question] Full dagger reflection support

### ISSUE THREAD

**Issue by molokoka** [soundcloud/delect#22]
Hello!

Your plugin is very useful, but do you plan to support full dagger reflection?

**Comment by runningcode** [comment]
By full dagger reflection do you mean [this](https://github.com/jakewharton/dagger-reflect#full-reflection)?
I can add a flag to a configuration extension which would not add the dagger reflect annotation processor? Would that work?

**Comment by runningcode** [comment]
Check out https://github.com/soundcloud/delect/pull/25 and let me know if that works for you!
