### ISSUE TITLE
Build fails with "Found more than one jar in the 'lintChecks' configuration"

### ISSUE THREAD

**Issue by lwasyl** [soundcloud/delect#27]
This happens after applying `id("com.soundcloud.delect")` (0.2.0) in root project's `build.gradle` file, and running the build with `./gradlew app:assembleDevDebug -Pdagger.reflect=true`. We have a mix of android-library and kotlin subprojects.

Output (`app` is the only application module in the project):
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:prepareLintJar'.
> Found more than one jar in the 'lintChecks' configuration. Only one file is supported. If using a separate Gradle project, make sure compilation dependencies are using compileOnly

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:prepareLintJar'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:185)
```

**Comment by runningcode** [comment]
This is a bug in AGP:
https://issuetracker.google.com/issues/141840950 

But we've gotten a lot of feedback about this. I'll add an option to disable the lint checks in the extension.

**Comment by lwasyl** [comment]
That was quick :) Any workaround I can apply locally for the time being?

**Comment by runningcode** [comment]
If you have other custom lint checks included in your build, you can comment them out.

**Comment by lwasyl** [comment]
Ah, I totally forgot we have custom lint checks project! That makes sense, thanks! I can confirm that after commenting it out things work (although it is a bit unfortunate we have to do that)

**Comment by runningcode** [comment]
I'm going to keep this open while working on a better workound.

**Comment by runningcode** [comment]
0.2.1 is released with the fix. Please try it out and let me know how it works for you.
https://github.com/soundcloud/delect#found-more-than-one-jar-in-the-lintchecks-configuration

**Comment by m4xp1** [comment]
Thanks! It's works for me.
