### ISSUE TITLE
Enable activation through extension property

### ISSUE THREAD

**Issue by realdadfish** [soundcloud/delect#34]
Right now the activation of the plugin is triggered through the `gradle.properties` property `dagger.reflect`. In certain circumstances it would however be cool to be able to dynamically trigger this option, either by a project parameter given to the command line or by redirecting to a file-based setting other than `gradle.properties`.

**Comment by runningcode** [comment]
This is a good request. I initially hesitated adding an extension property since that would mean cache misses and longer builds when switching the property via command line.
Can you tell me more about the use case?

**Comment by realdadfish** [comment]
My specific use case is to use a custom properties file where this is configured. We have `gradle.properties` for things that affect all builds and all custom build configurations go into some `project-config.properties-dist`, that the developer can copy and override per checkout.

**Comment by realdadfish** [comment]
The thing is - changes to `gradle.properties` go unnoticed to easily and are quickly checked in, things in `$HOME/.gradle/gradle.properties` on the other hand are too global, so this is our "middle ground".

**Comment by rciovati** [comment]
Hey Thomas, thanks for this feature requests. We're in the process of archiving this project as we don't plan to provide more support to Delect. If you're still interested in this feature, I'd recommend forking the project :)
