### ISSUE TITLE
No auto-navigation to the generated code in Android Studio

### ISSUE THREAD

**Issue by johncara** [soundcloud/delect#36]
When using delect with `dagger.reflect=true`, Android Studio doesn't automatically pick up the location of the generated Component. Can this be fixed or is there something I need to set?

With no entry for dagger.reflect in `gradle.properties`:
<img width="321" alt="Screenshot 2020-12-11 at 14 32 51" src="https://user-images.githubusercontent.com/29805726/101915721-e9a9a900-3bbd-11eb-8f63-09e2e02d687d.png">

vs

With `dagger.reflect=true` in `gradle.properties`:
<img width="323" alt="Screenshot 2020-12-11 at 14 33 47" src="https://user-images.githubusercontent.com/29805726/101915752-f4643e00-3bbd-11eb-94f6-e2f35e1f5267.png">

**Comment by runningcode** [comment]
Hi there @johncara, thanks for filing. To get more information are you using the partial refleciton approach or the full reflection approach? That is, do you have `addReflectAnnotationProcessor = false` set when using Delect?

**Comment by johncara** [comment]
Hi, thanks for the fast response! No, I haven't set `addReflectAnnotationProcessor` to any value. There is generated code for the `DaggerMainComponent` too so it's got to be the partial reflection approach.

**Comment by runningcode** [comment]
Ah that's correct then you would be using the partial refelction approach. In that case I would only expect there to be generated code for the `DaggerMainComponent`. The other components have no generated code.

**Comment by johncara** [comment]
Hi, yes I understand that partial refection results in only the `DaggerMainComponent` being created. The problem is that in the case where `dagger.reflect=true` (second image above), the generated `DaggerMainComponent` is not picked up by Android Studio (there are no green dots in the second image allowing you to step to the generated code).

**Comment by rciovati** [comment]
Hey John, thanks for this reporting this issue. We're in the process of archiving this project as we don't plan to provide more support to Delect. If you're still interested in fixing this issue, I'd recommend forking the project :)
